### ISSUE TITLE
"editor.fontSize" 14

### ISSUE THREAD

**Issue by cmcrothers** [basarat/god-extra#2]
When enabling this extension it always sets `"editor.fontSize": 14` in user settings and will overwrite whatever is there whenever VSCode is opened

**Comment by basarat** [comment]
Fixed with `0.0.40`. Moved it behind an explicit command: 

![image](https://user-images.githubusercontent.com/874898/38595659-6215c7b8-3d90-11e8-82d3-600f963ed1ba.png)

:rose:
