### ISSUE TITLE
god demo browser don't detect #root

### ISSUE THREAD

**Issue by Gi972** [basarat/god-extra#6]
Hello @basarat 

I try the god demo in browser

this is a capture , I'm miss something?

For precision , I juste create a create-react-app-typescript and test the mode demo.
my version vscode:1.27.2 on mac

![image](https://user-images.githubusercontent.com/1606247/45520635-88b28100-b7ba-11e8-8c12-22c3e10a560c.png)

**Comment by Gi972** [comment]
I try with a other boilerplate and it's work.
I close this. 
If you want more infos tell me

**Comment by basarat** [comment]
It doesn't come with any loader support beyond TypeScript. I don't require css in my project (cause of https://typestyle.github.io/#/) hence it will not work for your use case :rose:
