### ISSUE TITLE
errors inside node_modules

### ISSUE THREAD

**Issue by dontsave** [basarat/god-extra#7]
I love ts god mode! Especially love the project-wide error analysis. Is there a way to restrict the error analysis to just typescript files within the src for example? My only complaint is the plugin is currently showing "27 errors" apparently all of them in node_modules. The tsconfig docs show that node_modules is implicitly excluded. Do I need to make it explicit?

**Comment by basarat** [comment]
Add `skipLibCheck` to your tsconfig.json 👍 :rose:
