### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Fayipe** [basarat/god-extra#9]
- Issue Type: `Performance`
- Extension Name: `god`
- Extension Version: `0.0.72`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/mac/basarat.god-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by basarat** [comment]
Fixed `0.0.73` 

# Retro 
To enable reliable Jest file tree detection I would be recreating a ts builder. I've removed the jest support + typescript builder I was generating for now. Simplifying the project till I have time to do something better. Thanks :rose: :heart:
